name: Test Discord Action Download

on:
  workflow_dispatch: # Allows you to trigger it manually from the Actions tab

jobs:
  test_notify:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4 # Let's stick with v4 for now

      - name: Test Send Discord Notification
        uses: crazy-max/ghaction-discord@v4
        with:
          webhook_url: ${{ secrets.DISCORD_WEBHOOK }} # Make sure this secret is still valid
          content: "Minimal test: Can crazy-max/ghaction-discord be downloaded?"
        # Add a condition to avoid running if the secret is missing,
        # though the download error happens before this point.
        if: secrets.DISCORD_WEBHOOK != ''
